### PR TITLE
Add a mean squared error function

### PR DESCRIPTION
**Pull request by bensoltoff**
Adds support for a quality function to calculate mean squared error. A shortcut for `rmse(model, data)^2`

### CODE REVIEW

**Comment by hadley** [comment]
Why would you use `mse()` instead of `rmse()`?

**Comment by bensoltoff** [comment]
It maintains consistency with some common statistics textbooks. For example, in an Introduction to Statistical Learning the authors use MSE to evaluate accuracy of models with continuous dependent variables. I use that text commonly, so it's easier to implement that metric directly with a single function.

**Comment by hadley** [comment]
Makes sense!

**Comment by hadley** [comment]
Can you please add a bullet to NEWS? It should briefly describe the change (starting with name of the function), and crediting yourself with `(@yourname, #issuenumber)`.

**Comment by bensoltoff** [comment]
@hadley done.

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
