### PR TITLE
Add typical methods for ordered factors and integers

### PR DESCRIPTION
**Pull request by jrnold**
Add `typical` methods for `integer` and ordered factor vectors.

- integer: preserves the integer type instead of returning numeric
- ordered factor: returns the level of the 50% quantile instead of the most frequent.

### CODE REVIEW

**Comment by hadley** [comment]
Can you please add a bullet to NEWS? It should briefly describe the change (starting with name of the function), and crediting yourself with `(@yourname, #issuenumber)`.

**Comment by jrnold** [comment]
I updated news. I bumped the package version to a dev version `0.1.1.9000`

**Comment by hadley** [comment]
Let me fix the version number (done).

I think something went wrong with your rebase 😞

**Comment by jrnold** [comment]
Next best thing to burning it all down ... squashed the rebase until it worked.

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
